name: dice_icons
description: A package project contains dice icons from zero to six.
version: 0.1.6
homepage: https://www.leventkantaroglu.com
repository: https://github.com/leventkantaroglu/dice_icons

funding:
  - https://www.buymeacoffee.com/kantaroglu

screenshots:
  - description: "This screenshot shows a preview of dice icons."
    path: preview.png

topics:
  - icon
  - dice

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: DiceIcons
      fonts:
        - asset: lib/assets/fonts/MyFlutterApp.ttf
