name: dice_icons
description: A new Flutter package project.
version: 0.0.1
homepage: https://www.leventkantaroglu.com

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
   - family:  DiceIcons
     fonts:
      - asset: assets/fonts/MyFlutterApp.ttf